// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaInformationService.Infrastructure.Persistance;

#nullable disable

namespace PizzaInformationService.Infrastructure.Migrations
{
    [DbContext(typeof(PizzaInformationDbContext))]
    [Migration("20251208084928_AddSeeding")]
    partial class AddSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "PizzaId");

                    b.HasIndex("PizzaId");

                    b.ToTable("IngredientPizza");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            PizzaId = 1
                        },
                        new
                        {
                            IngredientsId = 2,
                            PizzaId = 1
                        },
                        new
                        {
                            IngredientsId = 3,
                            PizzaId = 1
                        },
                        new
                        {
                            IngredientsId = 1,
                            PizzaId = 2
                        },
                        new
                        {
                            IngredientsId = 2,
                            PizzaId = 2
                        },
                        new
                        {
                            IngredientsId = 4,
                            PizzaId = 2
                        },
                        new
                        {
                            IngredientsId = 5,
                            PizzaId = 3
                        },
                        new
                        {
                            IngredientsId = 6,
                            PizzaId = 3
                        },
                        new
                        {
                            IngredientsId = 7,
                            PizzaId = 3
                        });
                });

            modelBuilder.Entity("PizzaInformationService.Domain.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mozzarella Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fresh Basil"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grilled Chicken"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Red Onions"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cilantro"
                        });
                });

            modelBuilder.Entity("PizzaInformationService.Domain.Entities.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic pizza with tomato sauce, mozzarella cheese, and fresh basil.",
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Margherita",
                            Price = 13.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tomato sauce, mozzarella cheese, and pepperoni slices.",
                            ImageUrl = "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?q=80&w=1476&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Pepperoni Pizza",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "BBQ sauce, grilled chicken, red onions, and cilantro.",
                            ImageUrl = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=781&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "BBQ Chicken",
                            Price = 15.00m
                        });
                });

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.HasOne("PizzaInformationService.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaInformationService.Domain.Entities.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
